/**
 * Generates the renderer module that carries Shane's Atelier DSL.
 *
 * The interchange contract is a real FILE, so the tests read it from disk
 * rather than a string literal pasted into a test. The archive is a real zip,
 * so it is read with `unzip -p` rather than a hand-rolled deflate decoder.
 */

import { app } from 'electron'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'

const here = __dirname

const CANDIDATES = [
  path.join(os.homedir(), 'Downloads/atelier-ai-bundle.zip'),
  path.join(here, '../../reference/atelier-ai-bundle.zip'),
]

app.whenReady().then(() => {
  let dsl: string | null = null
  let source = ''

  for (const zip of CANDIDATES) {
    if (!fs.existsSync(zip)) continue
    try {
      const raw = execFileSync('unzip', ['-p', zip, 'component-dsl.json'], {
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024,
      })
      JSON.parse(raw) // validate before shipping it
      dsl = raw
      source = zip
      break
    } catch (e) {
      console.error(`[loom] could not read ${zip}:`, String(e).slice(0, 200))
    }
  }

  if (dsl) console.log(`[loom] atelier DSL embedded (${dsl.length} bytes) from ${source}`)
  else console.log('[loom] no atelier bundle found; interchange tests will report it')

  const target = path.join(here, '../../src/model/atelier-bundle.generated.ts')
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(
    target,
    `/* GENERATED by electron/embed-bundle.ts — do not edit by hand. */
/**
 * Shane's Atelier \`component-dsl.json\`, embedded verbatim.
 *
 * ${dsl ? `Read from ${path.basename(source)}.` : 'Not found at build time; interchange tests report the gap.'}
 */
export const ATELIER_BUNDLE: string | null = ${
      dsl ? JSON.stringify(dsl) : 'null'
    }
`,
    'utf8',
  )
  console.log(`[loom] wrote ${path.relative(process.cwd(), target)}`)
  app.exit(0)
})
