/**
 * Responsive layout, as generated CSS.
 *
 * WHY CONTAINER QUERIES AND NOT MEDIA QUERIES. The thing being designed is a
 * box — a page, a panel, an embed — so its own inline width is the honest
 * input, not the browser window. That is also what lets the editor's viewport
 * switcher work honestly: it changes the artboard's width, the container
 * re-evaluates, and the layout responds. With media queries the switcher
 * would have to resize the OS window, which is not a feature, it is a rumour.
 *
 * ONE STYLESHEET, THREE TARGETS. The editor canvas, the live preview and both
 * exports all inject exactly this string. So the layout you author against is
 * the layout that ships — the same trick the behaviour layer uses, and for the
 * same reason: a preview that lies about responsive behaviour is worse than no
 * preview at all.
 *
 * The cascade is deliberately boring: the BASE styles are inline and are the
 * desktop case, and each narrower breakpoint overrides them inside a
 * `@container` band. Widest-first in the file, so the order reads the way the
 * design does: desktop, then tablet, then phone.
 */

import {
  BREAKPOINTS,
  BREAKPOINT_BAND,
  type Breakpoint,
  type Document,
  type Node,
  type ResponsiveOverride,
} from '../model/types'

/** The name of the container every responsive document establishes. */
export const CONTAINER_NAME = 'loom'

/** True when this node carries any responsive override at all. */
export function isResponsive(node: Node): boolean {
  return node.responsive !== undefined && Object.keys(node.responsive).length > 0
}

/** The breakpoints this node overrides, narrowest first. */
export function nodeBreakpoints(node: Node): Breakpoint[] {
  if (!node.responsive) return []
  return BREAKPOINTS.filter((bp) => node.responsive?.[bp] !== undefined)
}

function decls(over: ResponsiveOverride): string[] {
  const out: string[] = []
  if (typeof over.x === 'number') out.push(`left:${over.x}px`)
  if (typeof over.y === 'number') out.push(`top:${over.y}px`)
  if (typeof over.w === 'number') out.push(`width:${over.w}px`)
  if (typeof over.h === 'number') out.push(`height:${over.h}px`)
  if (typeof over.opacity === 'number') out.push(`opacity:${over.opacity}`)
  // `display` is how a free node becomes a flow child at a narrower width, and
  // the reverse. This is the whole reason flow belongs in the responsive
  // surface: stacking a row of cards on a phone IS a layout change.
  if (typeof over.flow === 'boolean') {
    out.push(over.flow ? 'display:flex' : 'display:block')
    if (over.flow) {
      out.push('flex-direction:column')
      out.push('align-items:stretch')
    }
  }
  if (typeof over.visible === 'boolean') {
    out.push(over.visible ? 'display:revert' : 'display:none')
  }
  return out
}

/**
 * The generated stylesheet for one document. Empty string when nothing
 * responds, so a document with no overrides ships no rules at all.
 */
export function responsiveCss(doc: Document): string {
  const rules: string[] = []
  // Widest first: the desktop band is the base, and each narrower band has to
  // be able to win, so it comes later.
  for (const bp of [...BREAKPOINTS].reverse()) {
    const { min, max } = BREAKPOINT_BAND[bp]
    const cond =
      max === null
        ? `(min-width: ${min}px)`
        : min > 0
          ? `(min-width: ${min}px) and (max-width: ${max}px)`
          : `(max-width: ${max}px)`
    const body: string[] = []
    for (const node of Object.values(doc.nodes)) {
      const over = node.responsive?.[bp]
      if (!over) continue
      const d = decls(over)
      if (d.length === 0) continue
      body.push(`[data-loom-id="${node.id}"]{${d.join(';')}}`)
    }
    if (body.length === 0) continue
    rules.push(`@container ${CONTAINER_NAME} ${cond}{${body.join('\n')}}`)
  }
  if (rules.length === 0) return ''
  return [
    `/* Generated by Loom: per-breakpoint layout. Do not edit by hand. */`,
    `.loom-container{container-type:inline-size;container-name:${CONTAINER_NAME}}`,
    ...rules,
  ].join('\n')
}

/**
 * The viewport widths the editor offers, narrowest first. These are the
 * CONTAINER widths, not window widths: the artboard is the thing being
 * measured.
 */
export const VIEWPORTS: ReadonlyArray<{ id: Breakpoint; label: string; width: number }> = [
  { id: 'sm', label: 'Phone', width: 390 },
  { id: 'md', label: 'Tablet', width: 834 },
  { id: 'lg', label: 'Desktop', width: 1280 },
]

/** The viewport a given container width falls into. */
export function breakpointForWidth(width: number): Breakpoint {
  for (const bp of BREAKPOINTS) {
    const { min, max } = BREAKPOINT_BAND[bp]
    if (width >= min && (max === null || width <= max)) return bp
  }
  // Unreachable while the bands tile the space; fail wide rather than narrow,
  // so an out-of-range width still gets the base layout.
  return 'lg'
}
